import { useMemo, useState } from "react";
import { ConfusionMatrixChart, ModelComparisonChart } from "../../components/charts";
import { PanelHeading } from "../../components/PanelHeading";
import type { EvaluationCandidate, EvaluationReport, ThresholdAnalysis } from "../../types";

export type EvaluationStage = "binary" | "multiclass";

function percent(value: number | undefined, digits = 2) {
  return value == null ? "Not reported" : `${(value * 100).toFixed(digits)}%`;
}

function numberMetric(value: number | undefined, suffix = "") {
  return value == null ? "Not reported" : `${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}${suffix}`;
}

function splitValue(value: unknown) {
  if (Array.isArray(value)) return value.join(", ");
  if (typeof value === "boolean") return value ? "Yes" : "No";
  if (value == null) return "Not reported";
  return String(value);
}

function ThresholdCurve({ analysis }: { analysis: ThresholdAnalysis }) {
  const width = 720, height = 280, left = 54, top = 20, right = 18, bottom = 42;
  const plotWidth = width-left-right, plotHeight=height-top-bottom;
  const points=[...analysis.points].sort((a,b)=>a.threshold-b.threshold);
  const x=(value:number)=>left+Math.max(0,Math.min(1,value))*plotWidth;
  const y=(value:number)=>top+(1-Math.max(0,Math.min(1,value)))*plotHeight;
  const line=(key: "recall"|"precision"|"false_positive_rate"|"alert_rate")=>points.map((p)=>`${x(p.threshold)},${y(p[key])}`).join(" ");
  return <figure className="threshold-curve" tabIndex={0} aria-label="Scrollable detector threshold chart"><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-labelledby="threshold-chart-title threshold-chart-desc"><title id="threshold-chart-title">Detector validation metrics across thresholds</title><desc id="threshold-chart-desc">Recall, precision, false-positive rate and alert rate between zero and one, with the serving threshold marked.</desc>
    {[0,.25,.5,.75,1].map(value=><g key={value}><line x1={left} x2={width-right} y1={y(value)} y2={y(value)} className="threshold-grid"/><text x={left-8} y={y(value)+4} textAnchor="end">{Math.round(value*100)}%</text><text x={x(value)} y={height-14} textAnchor="middle">{value.toFixed(2)}</text></g>)}
    <line x1={x(analysis.operating_threshold)} x2={x(analysis.operating_threshold)} y1={top} y2={height-bottom} className="threshold-operating"/><text x={x(analysis.operating_threshold)+5} y={top+12}>Serving {analysis.operating_threshold.toFixed(3)}</text>
    <polyline points={line("recall")} className="threshold-line threshold-line--recall"/><polyline points={line("precision")} className="threshold-line threshold-line--precision"/><polyline points={line("false_positive_rate")} className="threshold-line threshold-line--fpr"/><polyline points={line("alert_rate")} className="threshold-line threshold-line--alert"/>
  </svg><figcaption><span className="legend-recall">Recall</span><span className="legend-precision">Precision</span><span className="legend-fpr">False-positive rate</span><span className="legend-alert">Alert rate</span></figcaption></figure>;
}

function champion(candidates: EvaluationCandidate[]) {
  return candidates.find((model) => model.selected || model.status === "active") ?? candidates[0];
}

export interface ModelEvaluationViewProps {
  stage: EvaluationStage;
  report: EvaluationReport | null;
  loading?: boolean;
  error?: string;
  fixtureMode?: boolean;
  onRetry?: () => void;
}

export function ModelEvaluationView({ stage, report, loading = false, error = "", fixtureMode = false, onRetry = () => undefined }: ModelEvaluationViewProps) {
  const [matrixMode, setMatrixMode] = useState<"raw" | "normalized">("raw");
  const candidates = report?.candidates ?? [];
  const active = champion(candidates);
  const support = useMemo(() => Object.entries(active?.support ?? {}).sort((left, right) => left[1] - right[1]), [active]);
  const taskName = stage === "binary" ? "Attack detector" : "Attack-family classifier";
  const split = report?.split_definition ?? {};
  const p95 = active?.operational_metrics?.p95_inference_latency_ms;
  const modelBytes = active?.operational_metrics?.serialized_model_size_bytes;

  return <div className="model-evaluation-view">
    <section className="evaluation-boundary" aria-labelledby="evaluation-boundary-title"><div><span className="eyebrow">Decision boundary</span><h2 id="evaluation-boundary-title">Offline evidence, not deployment validation</h2></div><p>Use this workspace to inspect candidate selection and held-out behavior under the recorded protocol. Production effectiveness still requires representative field evaluation.</p></section>
    {loading ? <div className="panel data-state" role="status">Loading {taskName.toLowerCase()} evidence…</div> : null}
    {fixtureMode && !report && !loading ? <div className="panel data-state" role="note">Connected evaluation evidence is not available in fixture mode. Serving descriptors are not reused as benchmark results.</div> : null}
    {error && !report ? <div className="panel data-state data-state--error" role="alert"><span>{error}</span><button className="secondary-button" type="button" onClick={onRetry}>Retry evaluation</button></div> : null}
    {!loading && !fixtureMode && !error && !report ? <div className="panel data-state">No evaluation report was returned for the {taskName.toLowerCase()}.</div> : null}
    {report && !candidates.length && !loading ? <div className="panel data-state">The evaluation report contains no {taskName.toLowerCase()} candidates.</div> : null}
    {report && candidates.length && active ? <>
      <section className="panel evaluation-protocol" aria-labelledby="evaluation-protocol-title"><div className="evaluation-protocol-heading"><div><span className="eyebrow">Recorded protocol</span><h2 id="evaluation-protocol-title">What this comparison measures</h2></div><span className="ops-state ops-state--warning">Offline only</span></div><dl><div><dt>Selected artifact</dt><dd>{active.name}</dd><dd className="evaluation-protocol-note mono">{active.version}</dd></div><div><dt>Split strategy</dt><dd>{splitValue(split.strategy ?? report.split_notes)}</dd><dd className="evaluation-protocol-note">{splitValue(split.stratified_by)}</dd></div><div><dt>Evaluation seeds</dt><dd>{report.evaluation_seeds?.length ? report.evaluation_seeds.join(" · ") : "Not reported"}</dd><dd className="evaluation-protocol-note">{report.evaluation_seeds?.length ?? 0} declared runs</dd></div><div><dt>Score meaning</dt><dd>{report.probability_calibrated ? "Calibrated probability" : "Model score"}</dd><dd className="evaluation-protocol-note">{report.probability_calibrated ? "Validation-fitted calibration" : "Do not interpret as probability"}</dd></div></dl><details className="evaluation-protocol-details"><summary>Exact split definition</summary>{Object.keys(split).length ? <dl>{Object.entries(split).map(([key, value]) => <div key={key}><dt>{key.replaceAll("_", " ")}</dt><dd>{splitValue(value)}</dd></div>)}</dl> : <p>No structured split definition was returned.</p>}</details></section>
      <div className="models-grid">
        <section className="panel model-summary"><span className="eyebrow">Selected {taskName}</span><h2>{active.name}</h2><p className="mono">{active.version}</p><div className="model-score"><strong>{active.macro_f1 == null ? "—" : (active.macro_f1 * 100).toFixed(1)}</strong><span>% held-out macro F1</span></div><div className="fact-list"><div><span>Validation selection score</span><b>{percent(active.selection_value)}</b></div><div><span>Held-out weighted F1</span><b>{percent(active.weighted_f1)}</b></div>{stage === "binary" ? <div><span>Held-out false-positive rate</span><b>{percent(active.false_positive_rate ?? undefined)}</b></div> : null}<div><span>Median latency</span><b>{numberMetric(active.inference_ms, " ms")}</b></div><div><span>p95 latency</span><b>{numberMetric(p95, " ms")}</b></div><div><span>Serialized size</span><b>{modelBytes == null ? "Not reported" : `${(modelBytes / 1024).toFixed(1)} KiB`}</b></div></div></section>
        <section className="panel model-chart-panel"><PanelHeading eyebrow="Candidate comparison" title={`${taskName} trade-offs`} description={stage === "binary" ? "Held-out quality is higher-is-better; false-positive rate and latency are lower-is-better." : "Held-out quality is higher-is-better and latency is lower-is-better; detector false-positive rate does not apply."} action={<span className="panel-heading-meta">{candidates.length} candidates</span>}/><div className="evaluation-chart-scroll" role="region" aria-label="Scrollable candidate comparison chart" tabIndex={0}><ModelComparisonChart className="evaluation-wide-chart" models={candidates} height={420} includeFalsePositiveRate={stage === "binary"}/></div><div className="preview-scroll" role="region" aria-label="Scrollable exact candidate metrics" tabIndex={0}><table><caption>Validation selection and held-out test metrics</caption><thead><tr><th scope="col">Candidate</th><th scope="col">Validation macro F1</th><th scope="col">Test macro F1</th><th scope="col">Test weighted F1</th>{stage === "binary" ? <th scope="col">Test FPR</th> : null}<th scope="col">Median latency</th><th scope="col">p95 latency</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.name}><th scope="row">{candidate.name}{candidate.selected ? " · selected" : ""}</th><td>{percent(candidate.validation_metrics?.macro_f1 ?? candidate.selection_value)}</td><td>{percent(candidate.macro_f1)}</td><td>{percent(candidate.weighted_f1)}</td>{stage === "binary" ? <td>{candidate.false_positive_rate == null ? "Not measured" : percent(candidate.false_positive_rate)}</td> : null}<td>{numberMetric(candidate.inference_ms, " ms")}</td><td>{numberMetric(candidate.operational_metrics?.p95_inference_latency_ms, " ms")}</td></tr>)}</tbody></table></div></section>
        <section className="panel matrix-panel"><PanelHeading eyebrow="Held-out error structure" title="Champion confusion matrix" description="Rows are actual classes; columns are predictions. The exact table can switch between counts and actual-class percentages."/><div className="matrix-toggle" role="group" aria-label="Confusion matrix table values"><button type="button" className="secondary-button" aria-pressed={matrixMode === "raw"} onClick={() => setMatrixMode("raw")}>Raw counts</button><button type="button" className="secondary-button" aria-pressed={matrixMode === "normalized"} onClick={() => setMatrixMode("normalized")}>Row percentages</button></div>{active.confusion_matrix?.length ? <div className="evaluation-chart-scroll" role="region" aria-label="Scrollable champion confusion matrix chart" tabIndex={0}><ConfusionMatrixChart className="evaluation-wide-chart" matrix={active.confusion_matrix} classes={active.classes} height={410}/></div> : <div className="chart-empty">No confusion matrix was returned for this stage.</div>}{active.confusion_matrix?.length ? <div className="preview-scroll" role="region" aria-label="Scrollable exact champion confusion matrix" tabIndex={0}><table><caption>{matrixMode === "raw" ? "Exact confusion counts" : "Percent within each actual class"}</caption><thead><tr><th scope="col">Actual \ predicted</th>{active.classes?.map((label) => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{active.confusion_matrix.map((row, rowIndex) => { const total = row.reduce((sum, value) => sum + value, 0); return <tr key={active.classes?.[rowIndex] ?? rowIndex}><th scope="row">{active.classes?.[rowIndex] ?? `Class ${rowIndex + 1}`}</th>{row.map((value, column) => <td key={column}>{matrixMode === "raw" ? value : `${(total ? value / total * 100 : 0).toFixed(1)}%`}</td>)}</tr>; })}</tbody></table></div> : null}</section>
        <section className="panel seed-panel"><PanelHeading eyebrow="Selection evidence" title="Declared-seed validation aggregate" description="Validation aggregates selected the champion. They are distinct from the held-out test results above."/><div className="preview-scroll" role="region" aria-label="Scrollable declared-seed validation aggregates" tabIndex={0}><table><caption>Candidate selection aggregates across {report.evaluation_seeds?.length ?? "the declared"} seeds</caption><thead><tr><th scope="col">Candidate</th><th scope="col">Mean validation macro F1</th>{stage === "binary" ? <th scope="col">Mean validation FPR</th> : null}<th scope="col">Mean p95 latency</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.name}><th scope="row">{candidate.name}{candidate.selected ? " · selected" : ""}</th><td>{percent(candidate.selection_summary?.mean_validation_macro_f1)}</td>{stage === "binary" ? <td>{percent(candidate.selection_summary?.mean_validation_false_positive_rate)}</td> : null}<td>{numberMetric(candidate.selection_summary?.mean_p95_inference_latency_ms, " ms")}</td></tr>)}</tbody></table></div></section>
        <section className="panel support-panel"><PanelHeading eyebrow="Evidence strength" title="Held-out class support" description="Low support makes per-class conclusions less stable, even when the headline score is strong."/>{support.length ? <div className="support-table">{support.map(([label, count]) => <div key={label} className={count < 30 ? "support-row support-row--rare" : "support-row"}><span>{label}</span><b>{count}</b><small>{count < 30 ? "rare class" : "test rows"}</small></div>)}</div> : <div className="chart-empty">Class support was not included in the evaluation response.</div>}</section>
        <section className="panel measurement-panel"><PanelHeading eyebrow="Interpretation" title="Measurement notes"/><div className="model-note">{report.measurement_notes.length ? report.measurement_notes.map((note) => <p key={note}>{note}</p>) : <p>No measurement limitations were returned with this report.</p>}</div></section>
        {stage === "binary" && report.threshold_analysis ? <section className="panel threshold-panel"><PanelHeading eyebrow="Operating policy" title="Detector threshold analysis" description={`Validation-set behavior across detector thresholds; the promoted detector ${report.probability_calibrated ? "reports calibrated probabilities" : "reports model scores without declared calibration"}.`}/><div className="fact-list threshold-facts"><div><span>Serving threshold</span><b>{report.threshold_analysis.operating_threshold.toFixed(3)}</b></div><div><span>Policy</span><b>{report.threshold_analysis.selection_policy ?? "Current threshold retained"}</b></div><div><span>Validation rows</span><b>{report.threshold_analysis.partition_rows ?? "Not reported"}</b></div></div><ThresholdCurve analysis={report.threshold_analysis}/><div className="preview-scroll" role="region" aria-label="Scrollable exact detector threshold metrics" tabIndex={0}><table><caption>Recall, precision, false-positive and alert rates by threshold</caption><thead><tr><th scope="col">Threshold</th><th scope="col">Recall</th><th scope="col">Precision</th><th scope="col">FPR</th><th scope="col">Alert rate</th></tr></thead><tbody>{report.threshold_analysis.points.map((point) => <tr className={Math.abs(point.threshold - report.threshold_analysis!.operating_threshold) < 1e-8 ? "operating-row" : ""} key={point.threshold}><td>{point.threshold.toFixed(3)}</td><td>{percent(point.recall, 1)}</td><td>{percent(point.precision, 1)}</td><td>{percent(point.false_positive_rate, 1)}</td><td>{percent(point.alert_rate, 1)}</td></tr>)}</tbody></table></div></section> : null}
        {stage === "binary" && report.cascade_evaluation ? <section className="panel cascade-panel"><PanelHeading eyebrow="Complete serving path" title="Binary → family cascade" description={report.cascade_evaluation.protocol ?? "Shared held-out split evaluation"}/><div className="result-summary"><div><span>Test rows</span><b>{report.cascade_evaluation.test_rows ?? "—"}</b></div><div><span>Detector false negatives</span><b>{report.cascade_evaluation.detector_false_negatives ?? "—"}</b></div><div><span>Cascade macro F1</span><b>{percent(report.cascade_evaluation.metrics?.macro_f1)}</b></div></div>{report.cascade_evaluation.confusion_matrix.length ? <div className="evaluation-chart-scroll" role="region" aria-label="Scrollable cascade confusion matrix chart" tabIndex={0}><ConfusionMatrixChart className="evaluation-wide-chart" matrix={report.cascade_evaluation.confusion_matrix} classes={report.cascade_evaluation.classes} height={430}/></div> : <div className="chart-empty">No cascade confusion matrix was returned.</div>}<div className="preview-scroll" role="region" aria-label="Scrollable exact cascade recall and support" tabIndex={0}><table><caption>Per-class cascade recall and support, including detector misses</caption><thead><tr><th scope="col">Actual class</th><th scope="col">Correct</th><th scope="col">Support</th><th scope="col">Recall</th></tr></thead><tbody>{report.cascade_evaluation.classes.map((label,index)=>{const row=report.cascade_evaluation!.confusion_matrix[index]??[];const classRows=report.cascade_evaluation!.class_support?.[label]??row.reduce((sum,value)=>sum+value,0);const correct=row[index]??0;return <tr key={label}><th scope="row">{label}</th><td>{correct}</td><td>{classRows}</td><td>{classRows?percent(correct/classRows):"—"}</td></tr>})}</tbody></table></div></section> : null}
      </div>
    </> : null}
  </div>;
}
